(() => {
'use strict';
const STORE_KEY='kukac3d-arcade-profiles-v1',SESSION_KEY='kukac3d-arcade-session-v1',ITERATIONS=210000;
const state={player:null},$=id=>document.getElementById(id),lang=()=>localStorage.getItem('kukac3d-lang')||'de';
const copy=key=>window.KUKAC_I18N?.[lang()]?.[key]??window.KUKAC_I18N?.de?.[key]??key;
function readStore(){try{const v=JSON.parse(localStorage.getItem(STORE_KEY)||'{"profiles":[]}');return Array.isArray(v.profiles)?v:{profiles:[]};}catch{return{profiles:[]};}}
const writeStore=s=>localStorage.setItem(STORE_KEY,JSON.stringify(s));
const b64=b=>btoa(String.fromCharCode(...b)),unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const randomSalt=()=>b64(crypto.getRandomValues(new Uint8Array(16)));
async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return b64(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:unb64(salt),iterations:ITERATIONS},key,256)));}
function safeEqual(a,b){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
const normal=v=>String(v||'').trim(),valid=v=>/^[\p{L}\p{N}_-]{3,20}$/u.test(v);
const emptyStats=()=>({highScore:0,highestLevel:1,totalGames:0,totalStars:0,totalCoins:0,bestCombo:0,starsRecovered:0,dragonSurvivals:0,royalStars:0});
const publicPlayer=p=>({nickname:p.nickname,...emptyStats(),...(p.stats||{})});
function ranked(){return readStore().profiles.map(publicPlayer).sort((a,b)=>b.highScore-a.highScore||b.highestLevel-a.highestLevel||a.nickname.localeCompare(b.nickname)).map((p,i)=>({...p,rank:i+1}));}
const findPlayer=n=>ranked().find(p=>p.nickname.toLocaleLowerCase()===String(n||'').toLocaleLowerCase())||null;
function message(text,kind='info'){const e=$('accountMessage');if(e){e.textContent=text||'';e.dataset.kind=kind;}}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setMode(mode){document.querySelectorAll('[data-account-pane]').forEach(e=>e.hidden=e.dataset.accountPane!==mode);document.querySelectorAll('[data-account-mode]').forEach(e=>e.classList.toggle('active',e.dataset.accountMode===mode));message('');}
function refreshIdentity(){const p=state.player&&findPlayer(state.player.nickname);if(p)state.player=p;const label=p?p.nickname:copy('guestLabel');if($('arcadeIdentity'))$('arcadeIdentity').textContent=p?'● '+label:label;if($('startIdentity'))$('startIdentity').textContent=p?label+' · #'+p.rank:label;}
function statsGrid(p){const items=[[copy('rankLabel'),p.rank?'#'+p.rank:'—'],[copy('highScoreLabel'),Number(p.highScore||0).toLocaleString()],[copy('highestLevelLabel'),p.highestLevel||1],[copy('gamesLabel'),p.totalGames||0],[copy('starsLabel'),p.totalStars||0],[copy('coinsLabel'),p.totalCoins||0],[copy('bestComboLabel'),p.bestCombo||0],[copy('savedStarsLabel'),p.starsRecovered||0],[copy('dragonLabel'),p.dragonSurvivals||0],[copy('royalStarsLabel'),p.royalStars||0]];return'<div class="profile-grid">'+items.map(([k,v])=>'<div><small>'+esc(k)+'</small><b>'+esc(v)+'</b></div>').join('')+'</div>';}
function rawProfile(n){return readStore().profiles.find(p=>p.nickname===n)||null;}
function profileEligible(){const p=state.player&&rawProfile(state.player.nickname);return !!(p&&p.privacyAcknowledgedAt&&p.age12PlusAcknowledgedAt);}
function fillMyProfile(){const box=$('myProfileSummary');if(!box)return;const p=state.player&&findPlayer(state.player.nickname);box.innerHTML=p?'<div class="profile-hero"><strong>'+esc(p.nickname)+'</strong><span>'+copy('localOnlyLabel')+'</span></div>'+statsGrid(p):'<p>'+copy('notLoggedIn')+'</p>';for(const id of['exportBackupBtn','copyBackupBtn'])if($(id))$(id).disabled=!p;const legacy=$('legacyEligibilityForm');if(legacy)legacy.hidden=!p||profileEligible();}
function restoreSession(){state.player=findPlayer(localStorage.getItem(SESSION_KEY));if(!state.player)localStorage.removeItem(SESSION_KEY);refreshIdentity();fillMyProfile();return state.player;}
async function register(e){e.preventDefault();if(!$('privacyAck')?.checked)return message(copy('privacyRequired'),'error');if(!$('ageAck')?.checked)return message(copy('ageRequired'),'error');const nickname=normal($('registerNickname').value),password=$('registerPassword').value;if(password!==$('registerPassword2').value)return message(copy('passwordMismatch'),'error');if(!valid(nickname))return message(copy('invalidNickname'),'error');if(password.length<8)return message(copy('invalidPassword'),'error');const store=readStore();if(store.profiles.some(p=>p.nickname.toLocaleLowerCase()===nickname.toLocaleLowerCase()))return message(copy('nicknameTaken'),'error');message(copy('workingLabel'));const salt=randomSalt();store.profiles.push({version:1,nickname,salt,hash:await passwordHash(password,salt),kdf:'PBKDF2-SHA-256',iterations:ITERATIONS,createdAt:new Date().toISOString(),privacyNoticeVersion:1,privacyAcknowledgedAt:new Date().toISOString(),ageGateVersion:1,age12PlusAcknowledgedAt:new Date().toISOString(),stats:emptyStats()});writeStore(store);localStorage.setItem(SESSION_KEY,nickname);restoreSession();setMode('profile');message(copy('accountCreated'),'success');}
async function login(e){e.preventDefault();const nickname=normal($('loginNickname').value),profile=readStore().profiles.find(p=>p.nickname.toLocaleLowerCase()===nickname.toLocaleLowerCase());if(!profile)return message(copy('invalidCredentials'),'error');message(copy('workingLabel'));if(!safeEqual(await passwordHash($('loginPassword').value,profile.salt),profile.hash))return message(copy('invalidCredentials'),'error');localStorage.setItem(SESSION_KEY,profile.nickname);restoreSession();setMode('profile');message(copy('loginSuccess'),'success');}
function logout(){localStorage.removeItem(SESSION_KEY);state.player=null;refreshIdentity();fillMyProfile();setMode('login');}
function deleteProfile(){if(!state.player)return;if(!confirm(copy('deleteProfileConfirm')))return;const store=readStore();store.profiles=store.profiles.filter(p=>p.nickname!==state.player.nickname);writeStore(store);localStorage.removeItem(SESSION_KEY);state.player=null;refreshIdentity();fillMyProfile();setMode('register');message(copy('profileDeleted'),'success');}
function backupFor(n){const p=readStore().profiles.find(x=>x.nickname===n);if(!p)throw Error('missing');return{format:'KUKAC_ARCADE_BACKUP',version:1,exportedAt:new Date().toISOString(),profile:p};}
const backupString=data=>'KUKAC1.'+b64(new TextEncoder().encode(JSON.stringify(data)));
function parseBackup(raw){const value=String(raw||'').trim(),json=value.startsWith('KUKAC1.')?new TextDecoder().decode(unb64(value.slice(7))):value,data=JSON.parse(json),p=data?.profile;if(data?.format!=='KUKAC_ARCADE_BACKUP'||data.version!==1||!p||!valid(p.nickname)||!p.salt||!p.hash||p.kdf!=='PBKDF2-SHA-256'||p.iterations!==ITERATIONS)throw Error('invalid');p.stats={...emptyStats(),...(p.stats||{})};return data;}
function importBackup(data){const store=readStore(),p=data.profile,i=store.profiles.findIndex(x=>x.nickname.toLocaleLowerCase()===p.nickname.toLocaleLowerCase());if(i>=0)store.profiles[i]=p;else store.profiles.push(p);writeStore(store);localStorage.setItem(SESSION_KEY,p.nickname);restoreSession();setMode('profile');message(copy('backupRestored'),'success');}
function downloadBackup(){if(!state.player)return;const blob=new Blob([JSON.stringify(backupFor(state.player.nickname),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kukac-arcade-'+state.player.nickname+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);message(copy('backupDownloaded'),'success');}
async function copyBackup(){if(!state.player)return;const value=backupString(backupFor(state.player.nickname));try{await navigator.clipboard.writeText(value);message(copy('backupCopied'),'success');}catch{$('recoveryCodeInput').value=value;setMode('recover');message(copy('copyFallback'));}}
function recover(e){e.preventDefault();try{importBackup(parseBackup($('recoveryCodeInput').value));}catch{message(copy('invalidRecovery'),'error');}}
async function importFile(e){const file=e.target.files?.[0];if(!file)return;try{importBackup(parseBackup(await file.text()));}catch{message(copy('invalidRecovery'),'error');}finally{e.target.value='';}}
function loadLeaderboard(){const list=$('leaderboardBody'),rows=ranked();if(list)list.innerHTML=rows.length?rows.map(p=>'<button class="leader-row player-link" data-nickname="'+esc(p.nickname)+'"><span class="rank">#'+p.rank+'</span><strong>'+esc(p.nickname)+'</strong><span>'+Number(p.highScore).toLocaleString()+'</span><small>LVL '+p.highestLevel+'</small></button>').join(''):'<p>'+copy('emptyLeaderboard')+'</p>';}
function showPlayer(n){const p=findPlayer(n);$('playerProfile').style.display='grid';$('playerProfileContent').innerHTML=p?'<div class="profile-hero"><strong>'+esc(p.nickname)+'</strong><span>#'+p.rank+'</span></div>'+statsGrid(p):'<p>'+copy('genericError')+'</p>';}
function startRun(){return state.player?.nickname||null;}
function submitRun(stats){if(!state.player)return null;const store=readStore(),p=store.profiles.find(x=>x.nickname===state.player.nickname);if(!p)return null;const s=p.stats={...emptyStats(),...(p.stats||{})};s.highScore=Math.max(s.highScore,Number(stats.score)||0);s.highestLevel=Math.max(s.highestLevel,Number(stats.level)||1);s.totalGames++;s.totalStars+=Number(stats.stars)||0;s.totalCoins+=Number(stats.coins)||0;s.bestCombo=Math.max(s.bestCombo,Number(stats.bestCombo)||0);s.starsRecovered+=Number(stats.starsRecovered)||0;s.dragonSurvivals+=Number(stats.dragonSurvivals)||0;s.royalStars+=Number(stats.royalStars)||0;writeStore(store);restoreSession();return{player:state.player};}
function openAccount(mode=state.player?'profile':'login'){$('account').style.display='grid';setMode(mode);fillMyProfile();}
function requireProfile(){if(!state.player){openAccount('register');message(copy('profileRequired'),'error');return false;}if(!profileEligible()){openAccount('profile');message(copy('ageRequired'),'error');return false;}return true;}
function confirmLegacyEligibility(e){e.preventDefault();if(!$('legacyPrivacyAck')?.checked)return message(copy('privacyRequired'),'error');if(!$('legacyAgeAck')?.checked)return message(copy('ageRequired'),'error');const store=readStore(),p=store.profiles.find(x=>x.nickname===state.player?.nickname);if(!p)return message(copy('genericError'),'error');const now=new Date().toISOString();p.privacyNoticeVersion=1;p.privacyAcknowledgedAt=now;p.ageGateVersion=1;p.age12PlusAcknowledgedAt=now;writeStore(store);restoreSession();fillMyProfile();message(copy('loginSuccess'),'success');}const close=id=>$(id).style.display='none';
function bind(){$('accountBtn')?.addEventListener('click',()=>openAccount());$('startIdentity')?.addEventListener('click',()=>openAccount());$('leaderboardBtn')?.addEventListener('click',()=>{$('leaderboard').style.display='grid';loadLeaderboard();});$('closeAccount')?.addEventListener('click',()=>close('account'));$('closeLeaderboard')?.addEventListener('click',()=>close('leaderboard'));$('closePlayerProfile')?.addEventListener('click',()=>close('playerProfile'));$('logoutBtn')?.addEventListener('click',logout);$('deleteProfileBtn')?.addEventListener('click',deleteProfile);$('loginForm')?.addEventListener('submit',login);$('registerForm')?.addEventListener('submit',register);$('legacyEligibilityForm')?.addEventListener('submit',confirmLegacyEligibility);$('recoverForm')?.addEventListener('submit',recover);$('backupFileInput')?.addEventListener('change',importFile);$('exportBackupBtn')?.addEventListener('click',downloadBackup);$('copyBackupBtn')?.addEventListener('click',copyBackup);document.querySelectorAll('[data-account-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.accountMode)));document.addEventListener('click',e=>{const b=e.target.closest('.player-link');if(b?.dataset.nickname)showPlayer(b.dataset.nickname);});}
bind();restoreSession();window.KUKAC_ACCOUNT={startRun,submitRun,loadMe:restoreSession,loadLeaderboard,showPlayer,requireProfile,refreshLabels:()=>{refreshIdentity();fillMyProfile();},get player(){return state.player;},get cloudAvailable(){return false;},__test:{readStore,parseBackup,backupFor,passwordHash,profileEligible}};
})();
