window.KUKAC_I18N={
de:{
scoreLabel:'Punkte',stages:['WIESE','STADION','KÖNIGSARENA','DRACHENTAL','NACHTARENA'],levelLabel:'Level',bestLabel:'Rekord',levelBanner:'LEVEL',nextLevel:'Nächstes Level:',pointsWord:'Punkte',ruleMove:'↔ BEWEGEN',ruleStar:'⭐ STERN HOLEN',ruleSurvive:'⚠ NICHT CRASHEN',eventRoyal:'KÖNIGLICHES EVENT',eventDragon:'DRACHENANGRIFF',starSaved:'STERN GERETTET +20',boostBonus:'BOOST-BONUS',lifeLost:'LEBEN VERLOREN',bounce:'ABGEPRALLT',lastLife:'LETZTES LEBEN',shieldHit:'SCHILD',royalStar:'KÖNIGSSTERN',guestLabel:"Gast",accountTitle:"Arcade ID",loginTab:"Login",registerTab:"Registrieren",recoverTab:"Wiederherstellen",profileTab:"Profil",nicknameLabel:"Nickname",passwordLabel:"Passwort",passwordAgainLabel:"Passwort wiederholen",passwordHelp:"Mindestens 8 Zeichen. Das Passwort wird nur als gesalzener Einweg-Hash gespeichert.",loginButton:"Einloggen",registerButton:"Arcade ID erstellen",saveRecovery:"Speichere diesen Wiederherstellungscode. Er wird nur einmal angezeigt.",recoverHelp:"Wenn Cookies gelöscht wurden und du deinen Nickname vergessen hast, gib den bei der Registrierung gespeicherten Recovery-Code ein.",recoveryCodeLabel:"Recovery-Code",recoverButton:"Nickname wiederherstellen",yourNickname:"Dein Nickname",logoutButton:"Ausloggen",leaderboardTitle:"Globale Rangliste",playerStatsTitle:"Spielerstatistik",notLoggedIn:"Nicht eingeloggt.",workingLabel:"Lädt…",highScoreLabel:"Highscore",highestLevelLabel:"Höchstes Level",gamesLabel:"Spiele",starsLabel:"Sterne",coinsLabel:"Münzen",bestComboLabel:"Beste Combo",savedStarsLabel:"Gerettete Sterne",dragonLabel:"Drachen überlebt",royalStarsLabel:"Königssterne",rankLabel:"Rang",passwordMismatch:"Passwörter stimmen nicht überein.",accountCreated:"Arcade ID erstellt.",loginSuccess:"Eingeloggt.",nicknameRecovered:"Nickname gefunden.",invalidNickname:"Nickname: 3–20 Zeichen, Buchstaben/Zahlen/_/-.",invalidPassword:"Passwort muss mindestens 8 Zeichen haben.",nicknameTaken:"Dieser Nickname ist bereits vergeben.",invalidCredentials:"Nickname oder Passwort ist falsch.",invalidRecovery:"Ungültiger Recovery-Code.",recoveryNotFound:"Kein Konto für diesen Recovery-Code gefunden.",cloudUnavailable:"Cloud-Rangliste ist auf diesem Host noch nicht aktiviert.",authRequired:"Bitte zuerst einloggen.",scoreRejected:"Ergebnis wurde von der Plausibilitätsprüfung abgelehnt.",genericError:"Etwas ist schiefgelaufen.",emptyLeaderboard:"Noch keine Ergebnisse.",
intro:'Die klassische Snake-Idee als modernes 3D-Arcade-Spiel. Sammle Sterne und Münzen, weiche Hindernissen aus, baue Combos auf und erreiche immer schnellere Levels.',
keyboardTitle:'⌨️ Tastatur',keyboardText:'Pfeile oder WASD · Leertaste = Pause · Shift = Boost',mobileTitle:'📱 Mobil',mobileText:'Richtungstasten oder Wischen · BOOST = Beschleunigen',starTitle:'⭐ Stern',starText:'+10 Punkte, der Wurm wird länger und die Combo steigt.',coinTitle:'🪙 Goldmünze',coinText:'Seltener Bonus: +25 Punkte, ohne Wachstum.',
startBtn:'SPIEL STARTEN',helpBtnText:'Vollständige Anleitung',helpTitle:'Wie <em>spielst du?</em>',
helpGoal:'<b>Ziel:</b> Sammle so viele Punkte wie möglich, ohne gegen Wände, Hindernisse oder dich selbst zu stoßen.',helpScore:'<b>Punkte:</b> Stern +10, seltene Goldmünze +25. Schnelles Sammeln baut einen Combo-Bonus auf.',helpLevels:'<b>Levels:</b> Alle 80 Punkte beginnt ein neues Level. Tempo und Hindernisse nehmen zu.',helpBoost:'<b>Boost:</b> Shift oder BOOST auf Mobilgeräten. Schneller, aber riskanter.',helpControls:'<b>Steuerung:</b> Pfeile/WASD, D-Pad oder Wischen. Leertaste: Pause, R: Neustart, M: Ton.',helpInvaders:'<b>Eindringlinge:</b> Soldaten, Drachen und Retro-Helden laufen aufs Feld. Du hast 5 Leben. Beim ersten Leben schützen dich 3 Schilde; danach kostet jeder schwere Treffer ein Leben.',helpRecord:'<b>Rekord:</b> Der Browser speichert deinen Bestwert lokal.',understood:'VERSTANDEN',gameOverTitle:'SPIEL <em>VORBEI</em>',restartBtn:'NOCHMAL',
raidDragon:'DRACHE!',raidInvader:'EINDRINGLING!',stolen:'GESTOHLEN! -5',collision:'TREFFER!',pause:'PAUSE',go:'LOS',result:(s,l,b)=>`Punkte: <b>${s}</b> · Level: <b>${l}</b> · Rekord: <b>${b}</b>`
},
tr:{
scoreLabel:'Puan',stages:['ÇAYIR','STADYUM','KRALİYET ARENASI','EJDERHA VADİSİ','GECE ARENASI'],levelLabel:'Seviye',bestLabel:'Rekor',levelBanner:'SEVİYE',nextLevel:'Sonraki seviye:',pointsWord:'puan',ruleMove:'↔ HAREKET',ruleStar:'⭐ YILDIZI AL',ruleSurvive:'⚠ ÇARPMA',eventRoyal:'KRALİYET ETKİNLİĞİ',eventDragon:'EJDERHA SALDIRISI',starSaved:'YILDIZ KURTARILDI +20',boostBonus:'BOOST BONUSU',lifeLost:'CAN KAYBEDİLDİ',bounce:'SEKME',lastLife:'SON CAN',shieldHit:'KALKAN',royalStar:'KRALİYET YILDIZI',guestLabel:"Misafir",accountTitle:"Arcade ID",loginTab:"Giriş",registerTab:"Kayıt",recoverTab:"Kurtar",profileTab:"Profil",nicknameLabel:"Takma ad",passwordLabel:"Şifre",passwordAgainLabel:"Şifre tekrar",passwordHelp:"En az 8 karakter. Şifre yalnızca tuzlanmış tek yönlü hash olarak saklanır.",loginButton:"Giriş yap",registerButton:"Arcade ID oluştur",saveRecovery:"Bu kurtarma kodunu kaydet. Yalnızca bir kez gösterilir.",recoverHelp:"Çerezler silinirse ve takma adını unutursan kayıt sırasında verilen kurtarma kodunu gir.",recoveryCodeLabel:"Kurtarma kodu",recoverButton:"Takma adı kurtar",yourNickname:"Takma adın",logoutButton:"Çıkış yap",leaderboardTitle:"Global sıralama",playerStatsTitle:"Oyuncu istatistikleri",notLoggedIn:"Giriş yapılmadı.",workingLabel:"Yükleniyor…",highScoreLabel:"En yüksek skor",highestLevelLabel:"En yüksek seviye",gamesLabel:"Oyun",starsLabel:"Yıldız",coinsLabel:"Para",bestComboLabel:"En iyi kombo",savedStarsLabel:"Kurtarılan yıldız",dragonLabel:"Ejderha kurtuluşu",royalStarsLabel:"Kraliyet yıldızı",rankLabel:"Sıra",passwordMismatch:"Şifreler eşleşmiyor.",accountCreated:"Arcade ID oluşturuldu.",loginSuccess:"Giriş yapıldı.",nicknameRecovered:"Takma ad bulundu.",invalidNickname:"Takma ad 3–20 karakter olmalı; harf, rakam, _ veya - kullan.",invalidPassword:"Şifre en az 8 karakter olmalı.",nicknameTaken:"Bu takma ad kullanılıyor.",invalidCredentials:"Takma ad veya şifre yanlış.",invalidRecovery:"Geçersiz kurtarma kodu.",recoveryNotFound:"Bu kodla eşleşen hesap yok.",cloudUnavailable:"Cloud sıralama bu hostta henüz aktif değil.",authRequired:"Önce giriş yap.",scoreRejected:"Skor doğrulama kontrolünü geçemedi.",genericError:"Bir hata oluştu.",emptyLeaderboard:"Henüz skor yok.",
intro:'Klasik Snake fikrinin modern 3D arcade yorumu. Yıldız ve para topla, engellerden kaç, kombo yap ve giderek hızlanan seviyelere ulaş.',
keyboardTitle:'⌨️ Klavye',keyboardText:'Ok tuşları veya WASD · Boşluk = Duraklat · Shift = Hızlan',mobileTitle:'📱 Mobil',mobileText:'Yön tuşları veya kaydırma · BOOST = Hızlan',starTitle:'⭐ Yıldız',starText:'+10 puan, solucan uzar ve kombo artar.',coinTitle:'🪙 Altın para',coinText:'Nadir bonus: +25 puan, uzatma yok.',
startBtn:'OYUNU BAŞLAT',helpBtnText:'Tam kullanım kılavuzu',helpTitle:'Nasıl <em>oynanır?</em>',
helpGoal:'<b>Amaç:</b> Duvara, engele veya kendi gövdende çarpmadan olabildiğince çok puan topla.',helpScore:'<b>Puanlama:</b> Yıldız +10, nadir altın para +25. Hızlı toplama kombo bonusu verir.',helpLevels:'<b>Seviyeler:</b> Her 80 puanda yeni seviye başlar. Hız ve engeller artar.',helpBoost:'<b>Boost:</b> Shift veya mobilde BOOST. Daha hızlı ama daha riskli.',helpControls:'<b>Kontrol:</b> Oklar/WASD, D-pad veya kaydırma. Boşluk: duraklat, R: yeniden başlat, M: ses.',helpInvaders:'<b>Davetsizler:</b> Askerler, ejderhalar ve retro kahramanlar sahaya girer. 5 canın var. İlk canda 3 kalkan hakkın vardır; sonra her ağır çarpışma bir can götürür.',helpRecord:'<b>Rekor:</b> En yüksek skor tarayıcıda yerel olarak saklanır.',understood:'ANLADIM',gameOverTitle:'OYUN <em>BİTTİ</em>',restartBtn:'TEKRAR',
raidDragon:'EJDERHA!',raidInvader:'DAVETSİZ!',stolen:'ÇALINDI! -5',collision:'ÇARPIŞMA!',pause:'DURAKLAT',go:'DEVAM',result:(s,l,b)=>`Puan: <b>${s}</b> · Seviye: <b>${l}</b> · Rekor: <b>${b}</b>`
},
uk:{
scoreLabel:'Очки',stages:['ЛУКА','СТАДІОН','КОРОЛІВСЬКА АРЕНА','ДОЛИНА ДРАКОНА','НІЧНА АРЕНА'],levelLabel:'Рівень',bestLabel:'Рекорд',levelBanner:'РІВЕНЬ',nextLevel:'Наступний рівень:',pointsWord:'очок',ruleMove:'↔ РУХАЙСЯ',ruleStar:'⭐ ВІЗЬМИ ЗІРКУ',ruleSurvive:'⚠ НЕ ВРІЖСЯ',eventRoyal:'КОРОЛІВСЬКА ПОДІЯ',eventDragon:'АТАКА ДРАКОНА',starSaved:'ЗІРКУ ВРЯТОВАНО +20',boostBonus:'BOOST-БОНУС',lifeLost:'ЖИТТЯ ВТРАЧЕНО',bounce:'ВІДСКОК',lastLife:'ОСТАННЄ ЖИТТЯ',shieldHit:'ЩИТ',royalStar:'КОРОЛІВСЬКА ЗІРКА',guestLabel:"Гість",accountTitle:"Arcade ID",loginTab:"Вхід",registerTab:"Реєстрація",recoverTab:"Відновлення",profileTab:"Профіль",nicknameLabel:"Нікнейм",passwordLabel:"Пароль",passwordAgainLabel:"Повторіть пароль",passwordHelp:"Мінімум 8 символів. Пароль зберігається лише як salted one-way hash.",loginButton:"Увійти",registerButton:"Створити Arcade ID",saveRecovery:"Збережи цей recovery-код. Він показується лише один раз.",recoverHelp:"Якщо cookies видалені й ти забув нікнейм, введи recovery-код, збережений під час реєстрації.",recoveryCodeLabel:"Recovery-код",recoverButton:"Відновити нікнейм",yourNickname:"Твій нікнейм",logoutButton:"Вийти",leaderboardTitle:"Глобальна таблиця",playerStatsTitle:"Статистика гравця",notLoggedIn:"Не виконано вхід.",workingLabel:"Завантаження…",highScoreLabel:"Рекорд",highestLevelLabel:"Найвищий рівень",gamesLabel:"Ігри",starsLabel:"Зірки",coinsLabel:"Монети",bestComboLabel:"Найкраще комбо",savedStarsLabel:"Врятовані зірки",dragonLabel:"Пережито драконів",royalStarsLabel:"Королівські зірки",rankLabel:"Місце",passwordMismatch:"Паролі не збігаються.",accountCreated:"Arcade ID створено.",loginSuccess:"Вхід виконано.",nicknameRecovered:"Нікнейм знайдено.",invalidNickname:"Нікнейм: 3–20 символів; літери, цифри, _ або -.",invalidPassword:"Пароль має містити щонайменше 8 символів.",nicknameTaken:"Цей нікнейм уже зайнятий.",invalidCredentials:"Неправильний нікнейм або пароль.",invalidRecovery:"Неправильний recovery-код.",recoveryNotFound:"Обліковий запис не знайдено.",cloudUnavailable:"Cloud-рейтинг на цьому хості ще не активований.",authRequired:"Спочатку увійди.",scoreRejected:"Результат не пройшов перевірку.",genericError:"Сталася помилка.",emptyLeaderboard:"Результатів ще немає.",
intro:'Сучасна 3D-аркадна версія класичної Snake. Збирай зірки й монети, оминай перешкоди, будуй комбо та переходь на дедалі швидші рівні.',
keyboardTitle:'⌨️ Клавіатура',keyboardText:'Стрілки або WASD · Пробіл = пауза · Shift = прискорення',mobileTitle:'📱 Мобільний',mobileText:'Кнопки напрямку або свайп · BOOST = прискорення',starTitle:'⭐ Зірка',starText:'+10 очок, черв’як стає довшим, а комбо зростає.',coinTitle:'🪙 Золота монета',coinText:'Рідкісний бонус: +25 очок без збільшення довжини.',
startBtn:'ПОЧАТИ ГРУ',helpBtnText:'Повна інструкція',helpTitle:'Як <em>грати?</em>',
helpGoal:'<b>Мета:</b> Набери якомога більше очок, не врізаючись у стіни, перешкоди чи власне тіло.',helpScore:'<b>Очки:</b> Зірка +10, рідкісна золота монета +25. Швидкий збір дає бонус-комбо.',helpLevels:'<b>Рівні:</b> Кожні 80 очок починається новий рівень. Швидкість і кількість перешкод зростають.',helpBoost:'<b>Boost:</b> Shift або кнопка BOOST на мобільному. Швидше, але ризикованіше.',helpControls:'<b>Керування:</b> Стрілки/WASD, D-pad або свайп. Пробіл: пауза, R: рестарт, M: звук.',helpInvaders:'<b>Порушники:</b> Солдати, дракони й ретро-герої вибігають на поле. Є 5 життів. На першому житті тебе захищають 3 щити; далі кожне серйозне зіткнення забирає життя.',helpRecord:'<b>Рекорд:</b> Найкращий результат зберігається локально у браузері.',understood:'ЗРОЗУМІЛО',gameOverTitle:'ГРУ <em>ЗАВЕРШЕНО</em>',restartBtn:'ЩЕ РАЗ',
raidDragon:'ДРАКОН!',raidInvader:'ПОРУШНИК!',stolen:'ВКРАЛИ! -5',collision:'ЗІТКНЕННЯ!',pause:'ПАУЗА',go:'СТАРТ',result:(s,l,b)=>`Очки: <b>${s}</b> · Рівень: <b>${l}</b> · Рекорд: <b>${b}</b>`
},
hu:{
scoreLabel:'Pont',stages:['RÉT','STADION','KIRÁLYI ARÉNA','SÁRKÁNYVÖLGY','ÉJSZAKAI ARÉNA'],levelLabel:'Szint',bestLabel:'Rekord',levelBanner:'SZINT',nextLevel:'Következő szint:',pointsWord:'pont',ruleMove:'↔ MOZOGJ',ruleStar:'⭐ SZEREZD MEG',ruleSurvive:'⚠ NE ÜTKÖZZ',eventRoyal:'KIRÁLYI ESEMÉNY',eventDragon:'SÁRKÁNYTÁMADÁS',starSaved:'CSILLAG MEGMENTVE +20',boostBonus:'BOOST BÓNUSZ',lifeLost:'ÉLET ELVESZETT',bounce:'LEPATTANÁS',lastLife:'UTOLSÓ ÉLET',shieldHit:'PAJZS',royalStar:'KIRÁLYI CSILLAG',guestLabel:"Vendég",accountTitle:"Arcade ID",loginTab:"Belépés",registerTab:"Regisztráció",recoverTab:"Visszaállítás",profileTab:"Profil",nicknameLabel:"Nicknév",passwordLabel:"Jelszó",passwordAgainLabel:"Jelszó újra",passwordHelp:"Minimum 8 karakter. A jelszó kizárólag sózott, egyirányú hashként tárolódik.",loginButton:"Belépés",registerButton:"Arcade ID létrehozása",saveRecovery:"Mentsd el ezt a visszaállító kódot. Csak egyszer jelenik meg.",recoverHelp:"Ha törölted a cookie-kat és elfelejtetted a nicknevedet, add meg a regisztrációkor elmentett recovery kódot.",recoveryCodeLabel:"Recovery kód",recoverButton:"Nicknév visszaállítása",yourNickname:"A nickneved",logoutButton:"Kilépés",leaderboardTitle:"Globális ranglista",playerStatsTitle:"Játékos statisztika",notLoggedIn:"Nincs bejelentkezve.",workingLabel:"Betöltés…",highScoreLabel:"Rekord",highestLevelLabel:"Legmagasabb szint",gamesLabel:"Játékok",starsLabel:"Csillagok",coinsLabel:"Érmék",bestComboLabel:"Legjobb kombó",savedStarsLabel:"Megmentett csillagok",dragonLabel:"Túlélt sárkányok",royalStarsLabel:"Királyi csillagok",rankLabel:"Helyezés",passwordMismatch:"A két jelszó nem egyezik.",accountCreated:"Arcade ID létrehozva.",loginSuccess:"Sikeres belépés.",nicknameRecovered:"Nicknév megtalálva.",invalidNickname:"A nicknév 3–20 karakter lehet: betű, szám, _ vagy -.",invalidPassword:"A jelszó legalább 8 karakter legyen.",nicknameTaken:"Ez a nicknév már foglalt.",invalidCredentials:"Hibás nicknév vagy jelszó.",invalidRecovery:"Érvénytelen recovery kód.",recoveryNotFound:"Ehhez a kódhoz nem tartozik fiók.",cloudUnavailable:"A cloud ranglista ezen a hoston még nincs aktiválva.",authRequired:"Előbb jelentkezz be.",scoreRejected:"Az eredményt a szerver plausibility ellenőrzése elutasította.",genericError:"Hiba történt.",emptyLeaderboard:"Még nincs eredmény.",
intro:'A klasszikus Snake modern, látványos 3D arcade újragondolása. Gyűjts csillagokat és érméket, kerüld az akadályokat, építs kombót és juss egyre gyorsabb szintekre.',
keyboardTitle:'⌨️ Billentyűzet',keyboardText:'Nyilak vagy WASD · Space = szünet · Shift = boost',mobileTitle:'📱 Mobil',mobileText:'Iránygombok vagy húzás · BOOST = gyorsítás',starTitle:'⭐ Csillag',starText:'+10 pont, hosszabb leszel és nő a kombó.',coinTitle:'🪙 Arany érme',coinText:'Ritka bónusz: +25 pont, nem növeszt.',
startBtn:'JÁTÉK INDÍTÁSA',helpBtnText:'Teljes használati útmutató',helpTitle:'Hogyan <em>játssz?</em>',
helpGoal:'<b>Cél:</b> Gyűjts minél több pontot anélkül, hogy falnak, akadálynak vagy saját magadnak ütköznél.',helpScore:'<b>Pontozás:</b> Csillag +10, ritka arany érme +25. Gyors gyűjtéssel kombóbónuszt építesz.',helpLevels:'<b>Szintek:</b> 80 pontonként új szint jön. Nő a sebesség és az akadályok száma.',helpBoost:'<b>Boost:</b> Shift vagy mobilon BOOST. Gyorsabb, de kockázatosabb.',helpControls:'<b>Irányítás:</b> Nyilak/WASD, D-pad vagy húzógesztus. Space: szünet, R: újrakezdés, M: hang.',helpInvaders:'<b>Betolakodók:</b> Katonák, sárkányok és retro hősök berohannak. 5 életed van. Az első életnél 3 pajzs véd, utána minden komoly ütközés egy életet vesz le.',helpRecord:'<b>Rekord:</b> A böngésző helyben elmenti a legjobb pontszámot.',understood:'ÉRTEM',gameOverTitle:'JÁTÉK <em>VÉGE</em>',restartBtn:'ÚJRA',
raidDragon:'SÁRKÁNY!',raidInvader:'BETOLAKODÓ!',stolen:'ELLOPTÁK! -5',collision:'ÜTKÖZÉS!',pause:'SZÜNET',go:'RAJT',result:(s,l,b)=>`Pontszám: <b>${s}</b> · Szint: <b>${l}</b> · Rekord: <b>${b}</b>`
},
en:{
scoreLabel:'Score',stages:['MEADOW','STADIUM','ROYAL ARENA','DRAGON VALLEY','NIGHT ARENA'],levelLabel:'Level',bestLabel:'Best',levelBanner:'LEVEL',nextLevel:'Next level:',pointsWord:'points',ruleMove:'↔ MOVE',ruleStar:'⭐ GET THE STAR',ruleSurvive:'⚠ DON’T CRASH',eventRoyal:'ROYAL EVENT',eventDragon:'DRAGON ATTACK',starSaved:'STAR SAVED +20',boostBonus:'BOOST BONUS',lifeLost:'LIFE LOST',bounce:'BOUNCE',lastLife:'LAST LIFE',shieldHit:'SHIELD',royalStar:'ROYAL STAR',guestLabel:"Guest",accountTitle:"Arcade ID",loginTab:"Login",registerTab:"Register",recoverTab:"Recover",profileTab:"Profile",nicknameLabel:"Nickname",passwordLabel:"Password",passwordAgainLabel:"Password again",passwordHelp:"Minimum 8 characters. The password is stored only as a salted one-way hash.",loginButton:"Login",registerButton:"Create Arcade ID",saveRecovery:"Save this recovery code. It is shown only once.",recoverHelp:"If cookies are deleted and you forgot your nickname, enter the recovery code saved at registration.",recoveryCodeLabel:"Recovery code",recoverButton:"Recover nickname",yourNickname:"Your nickname",logoutButton:"Logout",leaderboardTitle:"Global leaderboard",playerStatsTitle:"Player stats",notLoggedIn:"Not logged in.",workingLabel:"Loading…",highScoreLabel:"High score",highestLevelLabel:"Highest level",gamesLabel:"Games",starsLabel:"Stars",coinsLabel:"Coins",bestComboLabel:"Best combo",savedStarsLabel:"Saved stars",dragonLabel:"Dragon survivals",royalStarsLabel:"Royal stars",rankLabel:"Rank",passwordMismatch:"Passwords do not match.",accountCreated:"Arcade ID created.",loginSuccess:"Logged in.",nicknameRecovered:"Nickname recovered.",invalidNickname:"Nickname must be 3–20 characters: letters, numbers, _ or -.",invalidPassword:"Password must be at least 8 characters.",nicknameTaken:"That nickname is already taken.",invalidCredentials:"Incorrect nickname or password.",invalidRecovery:"Invalid recovery code.",recoveryNotFound:"No account matches that recovery code.",cloudUnavailable:"Cloud leaderboard is not activated on this host yet.",authRequired:"Please log in first.",scoreRejected:"The score failed the server plausibility check.",genericError:"Something went wrong.",emptyLeaderboard:"No scores yet.",
intro:'A modern 3D arcade take on classic Snake. Collect stars and coins, dodge obstacles, build combos and reach increasingly faster levels.',
keyboardTitle:'⌨️ Keyboard',keyboardText:'Arrow keys or WASD · Space = pause · Shift = boost',mobileTitle:'📱 Mobile',mobileText:'Direction buttons or swipe · BOOST = speed up',starTitle:'⭐ Star',starText:'+10 points, you grow longer and your combo increases.',coinTitle:'🪙 Gold coin',coinText:'Rare bonus: +25 points without growing.',
startBtn:'START GAME',helpBtnText:'Full instructions',helpTitle:'How to <em>play?</em>',
helpGoal:'<b>Goal:</b> Score as many points as possible without hitting walls, obstacles or yourself.',helpScore:'<b>Scoring:</b> Star +10, rare gold coin +25. Fast pickups build a combo bonus.',helpLevels:'<b>Levels:</b> A new level starts every 80 points. Speed and obstacles increase.',helpBoost:'<b>Boost:</b> Shift or BOOST on mobile. Faster, but riskier.',helpControls:'<b>Controls:</b> Arrows/WASD, D-pad or swipe. Space: pause, R: restart, M: sound.',helpInvaders:'<b>Invaders:</b> Soldiers, dragons and retro heroes enter the field. You have 5 lives. On the first life you get 3 shields; after that every major collision costs one life.',helpRecord:'<b>Best score:</b> Your browser stores the high score locally.',understood:'GOT IT',gameOverTitle:'GAME <em>OVER</em>',restartBtn:'AGAIN',
raidDragon:'DRAGON!',raidInvader:'INVADER!',stolen:'STOLEN! -5',collision:'HIT!',pause:'PAUSE',go:'GO',result:(s,l,b)=>`Score: <b>${s}</b> · Level: <b>${l}</b> · Best: <b>${b}</b>`
}
};
